"""empty message

Revision ID: 087234b5e042
Revises: a1fb15ed5b0d
Create Date: 2024-12-07 21:39:36.675208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087234b5e042'
down_revision = 'a1fb15ed5b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=60), nullable=False))
        batch_op.drop_column('pasword')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pasword', sa.VARCHAR(length=60), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
